name: discovery_api_dart_client_generator
version: 0.0.2
author: Gerwin Sturm (scarygami.net/+)
description: Create API Client libraries based on the API's Discovery documentation

dependencies:
  args: any
